# Generated by Django 4.2.1 on 2023-05-04 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormasDePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forma", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="factura",
            name="id",
        ),
        migrations.AddField(
            model_name="factura",
            name="documento",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="factura",
            name="fecha_creacion",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="factura",
            name="monto",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factura",
            name="numero_factura",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="factura",
            name="usuario",
            field=models.CharField(default="No User Data", max_length=150),
        ),
    ]
