# Generated by Django 4.2.1 on 2023-05-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0002_formasdepago_remove_factura_id_factura_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="forma_de_pago",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ventas.formasdepago",
                to_field="forma",
            ),
        ),
    ]
