# Generated by Django 4.2.1 on 2023-05-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0004_alter_factura_documento_alter_factura_numero_factura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="documento",
            field=models.FileField(null=True, upload_to="documents/facturas"),
        ),
    ]
