# Generated by Django 4.2.1 on 2023-05-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0005_alter_factura_documento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ganancias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField(default=2023)),
                ("mes", models.IntegerField(default=5)),
                ("dia", models.IntegerField(default=19)),
                ("ganacia", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NumeroDeClientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField(default=2023)),
                ("mes", models.IntegerField(default=5)),
                ("dia", models.IntegerField(default=19)),
                ("numero_clientes", models.BigIntegerField(null=True)),
            ],
        ),
    ]
