# Generated by Django 4.2.1 on 2023-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0007_rename_ganacia_ganancias_ganancia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ganancias",
            name="dia",
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name="numerodeclientes",
            name="dia",
            field=models.IntegerField(default=22),
        ),
    ]
