# Generated by Django 4.2.1 on 2023-05-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0008_alter_ganancias_dia_alter_numerodeclientes_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ganancias",
            name="dia",
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name="numerodeclientes",
            name="dia",
            field=models.IntegerField(default=23),
        ),
    ]
