# Generated by Django 4.2.1 on 2023-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_remove_usuario_prueba_usuario_is_cajero_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrecioDolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.BigIntegerField(default=1)),
            ],
        ),
    ]
