# Generated by Django 4.2.1 on 2023-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_preciodolar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preciodolar",
            name="precio",
            field=models.FloatField(default=1),
        ),
    ]
