# Generated by Django 4.2.1 on 2023-05-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0005_datosempresa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datosempresa",
            name="telefono",
            field=models.IntegerField(),
        ),
    ]
