# Generated by Django 4.1.7 on 2023-04-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("destacado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorías",
                "db_table": "categorias",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True, max_length=1000)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=6)),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=6)),
                ("stock", models.PositiveIntegerField()),
                ("cantidad_comprada", models.PositiveIntegerField(default=0)),
                ("cantidad_vendida", models.PositiveIntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "producto",
                "ordering": ["id"],
            },
        ),
    ]
