# Generated by Django 4.1.7 on 2023-04-02 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="cantidad_comprada",
        ),
    ]
