# Generated by Django 4.1.7 on 2023-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_remove_producto_cantidad_comprada"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="cantidad_comprada",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
