# Generated by Django 4.1.7 on 2023-04-07 15:02

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_producto_cantidad_comprada"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="codigo_de_barras",
            field=models.CharField(default="0000000000000", max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="nombre", unique=True
            ),
        ),
    ]
