# Generated by Django 4.1.7 on 2023-04-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_producto_codigo_de_barras_producto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(),
        ),
    ]
