# Generated by Django 4.1.7 on 2023-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_alter_producto_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="execento_de_impuesto",
            field=models.BooleanField(default=False),
        ),
    ]
