# Generated by Django 4.2.1 on 2023-05-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_producto_execento_de_impuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='execento_de_impuesto',
            new_name='exento_de_impuesto',
        ),
    ]
