# Generated by Django 4.2.1 on 2023-05-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("direccion", models.TextField(default="Sin dirección")),
                ("numero_telefono", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenDeCompra",
            fields=[
                ("numero_orden", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField(null=True)),
                ("monto", models.BigIntegerField()),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compras.proveedor",
                    ),
                ),
            ],
        ),
    ]
