# Generated by Django 4.2.1 on 2023-05-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordendecompra",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="ordendecompra",
            name="archivo",
            field=models.FileField(null=True, upload_to="documents/ordenescompra"),
        ),
    ]
