# Generated by Django 4.2.1 on 2023-05-12 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0002_remove_ordendecompra_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordendecompra",
            name="fecha_orden",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
