# Generated by Django 4.2.1 on 2023-05-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0003_ordendecompra_fecha_orden"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perdida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField(default=2023)),
                ("mes", models.IntegerField(default=5)),
                ("dia", models.IntegerField(default=19)),
                ("perdida", models.BigIntegerField(null=True)),
            ],
        ),
    ]
