# Generated by Django 4.2.1 on 2023-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0005_alter_ordendecompra_numero_orden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perdida",
            name="dia",
            field=models.IntegerField(default=22),
        ),
    ]
