# Generated by Django 4.2.1 on 2023-05-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0006_alter_perdida_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perdida",
            name="dia",
            field=models.IntegerField(default=23),
        ),
    ]
