# Generated by Django 4.2.1 on 2023-06-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0007_alter_perdida_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perdida",
            name="dia",
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name="perdida",
            name="mes",
            field=models.IntegerField(default=6),
        ),
    ]
